#!/usr/bin/env node
// Generates platform token files from tokens.json — the single source of truth.
//   node packages/design-tokens/build.mjs
// Emits:
//   app/lib/theme/tokens.g.dart   (Flutter)
//   web/app/tokens.g.css          (Next.js CSS custom properties)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const t = JSON.parse(readFileSync(resolve(root, "packages/design-tokens/tokens.json"), "utf8"));

const camel = (s) => s.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

// ── Flutter: only pure hex/rgba we can map to Color; rgba → Color.fromRGBO ──
function dartColor(v) {
  if (v.startsWith("#")) {
    const hex = v.slice(1);
    const full = hex.length === 6 ? "FF" + hex : hex; // assume opaque
    return `const Color(0x${full.toUpperCase()})`;
  }
  const m = v.match(/rgba?\(([^)]+)\)/);
  if (m) {
    const [r, g, b, a = "1"] = m[1].split(",").map((x) => x.trim());
    return `const Color.fromRGBO(${r}, ${g}, ${b}, ${a})`;
  }
  throw new Error("unmapped color " + v);
}

let dart = `// GENERATED by packages/design-tokens/build.mjs — do not edit by hand.\n`;
dart += `import 'package:flutter/material.dart';\n\n`;
dart += `/// KnowBody design tokens (${t.$meta.name}).\nabstract final class KbTokens {\n`;
for (const [k, o] of Object.entries(t.color)) dart += `  static const Color ${camel(k)}Color = ${dartColor(o.value).replace(/^const /, "")};\n`;
dart += `\n  // radius\n`;
for (const [k, o] of Object.entries(t.radius)) dart += `  static const double radius${k[0].toUpperCase() + k.slice(1)} = ${o.value};\n`;
dart += `\n  // spacing\n`;
for (const [k, o] of Object.entries(t.space)) dart += `  static const double space${k.replace("2xl", "2xl").toUpperCase()} = ${o.value};\n`;
dart += `\n  static const String fontFamily = '${t.font.family.value}';\n`;
dart += `}\n`;
mkdirSync(resolve(root, "app/lib/theme"), { recursive: true });
writeFileSync(resolve(root, "app/lib/theme/tokens.g.dart"), dart);

// ── Web: CSS custom properties ──
let css = `/* GENERATED by packages/design-tokens/build.mjs — do not edit by hand. */\n:root {\n`;
for (const [k, o] of Object.entries(t.color)) css += `  --kb-${k}: ${o.value};\n`;
for (const [k, o] of Object.entries(t.radius)) css += `  --kb-radius-${k}: ${o.value}px;\n`;
for (const [k, o] of Object.entries(t.space)) css += `  --kb-space-${k}: ${o.value}px;\n`;
css += `  --kb-font: '${t.font.family.value}', ${t.font.family.fallback};\n`;
css += `  --kb-shadow-card: ${t.shadow.card.value};\n`;
css += `}\n`;
mkdirSync(resolve(root, "web/app"), { recursive: true });
writeFileSync(resolve(root, "web/app/tokens.g.css"), css);

console.log("✓ tokens → app/lib/theme/tokens.g.dart, web/app/tokens.g.css");
