-- Starter Thai food composition seed (per 100 g edible portion).
-- Approximate values for MVP; replace/extend with INMU Thai Food Composition DB under license.
INSERT INTO thai_foods (name_th, name_en, aliases, kcal_100g, protein_100g, carbs_100g, fat_100g) VALUES
('ข้าวสวย',                'Steamed jasmine rice', ARRAY['ข้าว','rice','khao'],              130, 2.7, 28.0, 0.3),
('ข้าวเหนียว',             'Sticky rice',          ARRAY['glutinous rice','khao niao'],       97, 2.0, 21.0, 0.2),
('ข้าวผัด',                'Fried rice',           ARRAY['khao pad'],                        163, 4.5, 24.0, 5.5),
('ผัดกะเพราหมูสับ',        'Pad kaprao (minced pork basil)', ARRAY['kaprao','krapow','basil pork'], 210, 12.0, 9.0, 14.0),
('ไข่ดาว',                 'Fried egg',            ARRAY['fried egg','khai dao'],            196, 13.6, 0.8, 15.0),
('ไก่ย่าง',                'Grilled chicken',      ARRAY['gai yang','grilled chicken'],      165, 27.0, 0.0, 6.0),
('อกไก่',                  'Chicken breast',       ARRAY['chicken breast','ok gai'],         120, 23.0, 0.0, 2.6),
('หมูปิ้ง',                'Grilled pork skewer',  ARRAY['moo ping'],                        240, 18.0, 6.0, 16.0),
('ส้มตำ',                  'Papaya salad',         ARRAY['som tam','somtum'],                 60, 1.5, 12.0, 1.0),
('ต้มยำกุ้ง',              'Tom yum goong',        ARRAY['tom yum','tom yam'],                45, 4.0, 3.5, 1.8),
('แกงเขียวหวานไก่',        'Green curry chicken',  ARRAY['green curry','gaeng keow wan'],    130, 8.0, 6.0, 8.5),
('ผัดไทย',                 'Pad thai',             ARRAY['pad thai'],                        190, 8.0, 27.0, 6.0),
('ก๋วยเตี๋ยวน้ำ',          'Noodle soup',          ARRAY['guay teow','noodle soup'],          90, 5.0, 12.0, 2.5),
('ข้าวมันไก่',             'Chicken rice (khao man gai)', ARRAY['khao man gai','hainanese'],  185, 9.0, 22.0, 7.0),
('ข้าวหมูแดง',            'Red pork over rice',   ARRAY['khao moo dang'],                   175, 8.5, 24.0, 5.5),
('ผัดผักบุ้ง',            'Stir-fried morning glory', ARRAY['pad pak boong'],                75, 2.5, 6.0, 4.5),
('แกงจืด',                 'Clear soup',           ARRAY['gaeng jued'],                       40, 3.0, 3.0, 1.5),
('มะม่วง',                 'Mango',                ARRAY['mango','mamuang'],                  60, 0.8, 15.0, 0.4),
('กล้วย',                  'Banana',               ARRAY['banana','kluay'],                   89, 1.1, 23.0, 0.3),
('โยเกิร์ต',               'Yoghurt',              ARRAY['yoghurt','yogurt'],                 61, 3.5, 4.7, 3.3),
('ข้าวโอ๊ต',               'Oats',                 ARRAY['oats','oatmeal'],                  389, 16.9, 66.0, 6.9),
('กาแฟเย็น',               'Thai iced latte',      ARRAY['iced latte','oliang','coffee'],     90, 2.0, 12.0, 3.5),
('ชาไทย',                  'Thai iced tea',        ARRAY['cha yen','thai tea'],              130, 1.5, 22.0, 4.0),
('น้ำเปล่า',               'Water',                ARRAY['water','nam plao'],                  0, 0.0, 0.0, 0.0),
('ไข่ต้ม',                 'Boiled egg',           ARRAY['boiled egg','khai tom'],           155, 13.0, 1.1, 11.0),
('ปลาทู',                  'Mackerel',             ARRAY['pla too','mackerel'],              205, 19.0, 0.0, 14.0),
('เต้าหู้',                'Tofu',                 ARRAY['tofu','taohu'],                     76, 8.0, 1.9, 4.8),
('สลัดผัก',                'Vegetable salad',      ARRAY['salad'],                            35, 1.5, 5.0, 1.2),
('ข้าวเหนียวมะม่วง',       'Mango sticky rice',    ARRAY['khao niao mamuang'],               230, 3.0, 45.0, 4.5),
('น้ำอัดลม',               'Soft drink',           ARRAY['soda','soft drink','coke'],         42, 0.0, 10.6, 0.0);
