// GENERATED by packages/design-tokens/build.mjs — do not edit by hand.
import 'package:flutter/material.dart';

/// KnowBody design tokens (KnowBody design tokens).
abstract final class KbTokens {
  static const Color limeColor = Color(0xFFD8FB4F);
  static const Color limeDeepColor = Color(0xFFA8C93A);
  static const Color limeStemColor = Color(0xFF8FA83A);
  static const Color limePaleColor = Color(0xFFEDF7C4);
  static const Color inkColor = Color(0xFF121212);
  static const Color inkSoftColor = Color.fromRGBO(18, 18, 18, 0.55);
  static const Color inkFaintColor = Color.fromRGBO(18, 18, 18, 0.40);
  static const Color bgColor = Color(0xFFEDEDE7);
  static const Color surfaceColor = Color(0xFFF6F6F2);
  static const Color cardColor = Color(0xFFFFFFFF);
  static const Color cardWarmColor = Color(0xFFFFFDF5);
  static const Color darkColor = Color(0xFF0E120E);
  static const Color darkElevColor = Color(0xFF1E2A16);
  static const Color darkNightColor = Color(0xFF1A2018);
  static const Color onDarkColor = Color(0xFFFFFFFF);
  static const Color onDarkSoftColor = Color.fromRGBO(255, 255, 255, 0.55);
  static const Color accentTextColor = Color(0xFF6E8B00);
  static const Color accentDeepColor = Color(0xFF3F4A16);
  static const Color petFurColor = Color(0xFFF4F1E6);
  static const Color petBellyColor = Color(0xFFFFFDF5);
  static const Color petNoseColor = Color(0xFFE9A395);
  static const Color petEyeColor = Color(0xFF20241D);
  static const Color petCheekColor = Color.fromRGBO(233, 163, 149, 0.5);
  static const Color hairlineColor = Color.fromRGBO(18, 18, 18, 0.08);
  static const Color dangerColor = Color(0xFFE5484D);

  // radius
  static const double radiusChip = 12;
  static const double radiusButton = 18;
  static const double radiusPill = 20;
  static const double radiusCard = 24;
  static const double radiusCardLg = 28;
  static const double radiusHero = 36;
  static const double radiusFull = 999;

  // spacing
  static const double spaceXS = 6;
  static const double spaceSM = 10;
  static const double spaceMD = 14;
  static const double spaceLG = 20;
  static const double spaceXL = 24;
  static const double space2XL = 32;

  static const String fontFamily = 'Prompt';
}
